### ISSUE TITLE
Trouble displaying alarms in browser

### ISSUE THREAD

**Issue by Gbengat** [carlosperate/LightUpPi-Alarm#2]
Hello Carlos, first let me say this is an awesome project. CLi mode works great. I can view, edit, create alarms. However I have a small issue, I am not able to see the alarms created in any browser when running in server mode. Rather it loads the default demo alarms. Same goes for the weather forecast, it just has the default TBD icons. Any way I can fix this would really be appreciated.

**Comment by carlosperate** [comment]
Hi @Gbengat ,

Can you try to access the web interface within the same computer (I assume raspberry pi?) where the command line interface is being executed? So if running on a RasPi, could you open a browser in the Pi, and go to http://localhost/LightUpPi ? Does the same problem manifest there?

**Comment by Gbengat** [comment]
@carlosperate Thank you for your swift reply. I Just tried it directly on the Pi hosting it and it loaded up the alarms I created through CLi correctly. However adding new alarms from the browser doesn't work and weather still gives an error. I can't delete alarms either.

**Comment by Gbengat** [comment]
Hi @carlosperate , I thought I'd also note. On deleting all alarms in CLi and then running in server mode, the server crashes. This is all on the raspberry pi. 
![screenshot from 2016-11-21 14-53-49](https://cloud.githubusercontent.com/assets/5658092/20482023/35bfb04e-affb-11e6-8b74-8dc64c1a4c54.png)

**Comment by Gbengat** [comment]
Thank you for your help.
